language: scala
scala:
- 2.10.0
before_script:
- ./adjust_config.sh
- ./create_version_info.sh
script:
- sbt test
env:
  global:
  - secure: iJ5mIr1AnFSSMOEaNe5mW7QnUIQfb7EJnlp3c9dkmwFNMcNjUKd0Rv0cfpPKbtFiJAeT64D9hYcneCTDbpG+CLLKuC6LytEJYlckcLqfGioOS6NLzBzttLkh3Uh5ti8qxAnTKE2LPYfzi86FCDfBTfuW/16Coxtk2XpBytpVMK4=
  - secure: EGADJFjMAj7EH8hkpvb6dTTbhLxybcSJ5zQmMJNww4a1nH35RTP80adGhjAH0JNPgmHiWT8nLAmD0kYZ/ChiOoCEvu1If1aYXwJCo0UzhQQYNoDfw+fFu4VAvhPsHk8xQTo2/VqSy/5KciHVo9Im84me60ARAy2aRoBjELAhS0s=
  - secure: h07qpmSXIpW/DUmncpxR2M3DnhwUpV54e23kZFuJeaxrEqxdZn/ICI2B/BSsC1HyKXYLgLTfYEL3MnTNI3m3z9ywGku6ywWfH4X2jD6COI7XdBFqTRx3pEK+75niyqY7TB7BuXAw86ExzLQj4xKh1Q+3ysqFtJRdvY8uvfiA0FA=
  - secure: O8/e3bNXFlJOGqmQh8CMfmW/fj+6WZNQsyugKOcqV2EIZFE8qCeKGPfEbjRib7h3yIuv9HGTglIdzwrUK2YhhEjcqfCf811J/rHSYL4TH/xwQOJPSgxJiBm9m/P8BBS3KdEefbmAYw/WXn0i2TnsbERyqXESFOUibTy8imizNaY=
deploy:
  provider: heroku
  api_key:
    secure: VArEXrt9DBeh12bhlxOAF8P++AB+n1AqOTjeN6iRXXyjlGRZxKwuqpKfQeLO5YF59sEf0C96U9RbLfW8RgZLCd+fPOjyp8xJGIyAcQ0HokZoTqRKdB07ixDEu3ZQLEG2V48kWDD2wsqhTCmoMM0PEaMQUgWFWj1SkkfeJkQgf/U=
