language: scala
scala:
- 2.10.0
before_script:
- "./adjust_config.sh"
- "./create_version_info.sh"
script:
- sbt test
env:
  global:
  - secure: iJ5mIr1AnFSSMOEaNe5mW7QnUIQfb7EJnlp3c9dkmwFNMcNjUKd0Rv0cfpPKbtFiJAeT64D9hYcneCTDbpG+CLLKuC6LytEJYlckcLqfGioOS6NLzBzttLkh3Uh5ti8qxAnTKE2LPYfzi86FCDfBTfuW/16Coxtk2XpBytpVMK4=
  - secure: EGADJFjMAj7EH8hkpvb6dTTbhLxybcSJ5zQmMJNww4a1nH35RTP80adGhjAH0JNPgmHiWT8nLAmD0kYZ/ChiOoCEvu1If1aYXwJCo0UzhQQYNoDfw+fFu4VAvhPsHk8xQTo2/VqSy/5KciHVo9Im84me60ARAy2aRoBjELAhS0s=
  - secure: h07qpmSXIpW/DUmncpxR2M3DnhwUpV54e23kZFuJeaxrEqxdZn/ICI2B/BSsC1HyKXYLgLTfYEL3MnTNI3m3z9ywGku6ywWfH4X2jD6COI7XdBFqTRx3pEK+75niyqY7TB7BuXAw86ExzLQj4xKh1Q+3ysqFtJRdvY8uvfiA0FA=
  - secure: YtAVMeNQVQ0uC3b2YRTS+OWBJbYA8YHxO+IcEY9Em7skreR7PXee3xj4sjN7HgwcxtOeBpkTy5oWfARqDx38f6nbLpsOSS8IP2nnud28YzVq8qGTcf/pnUzEu8+e02QdiihU91XVI5I2nDWhgbeFMlP7+Rjf9ImjAAPXH/efhko=
  - secure: hFAWuZZUXqmL6WUwfc7VF5vdkr7B8jWTpqQncPKavtpM2z5cy6wC5tu4pk/0zlZspOpbJNWMVQ+pq8cpMgxbeonr5NLQzg7qjiNIXOomXgAwPCZbWRPO4K650CDASzzj3sI6QUCn7BKuauOjAS321EbQuCR2lC6LOl5p9pzLf/c=
  - secure: O8/e3bNXFlJOGqmQh8CMfmW/fj+6WZNQsyugKOcqV2EIZFE8qCeKGPfEbjRib7h3yIuv9HGTglIdzwrUK2YhhEjcqfCf811J/rHSYL4TH/xwQOJPSgxJiBm9m/P8BBS3KdEefbmAYw/WXn0i2TnsbERyqXESFOUibTy8imizNaY=
deploy:
  provider: heroku
  api_key:
    secure: ZKkGHArzu61yMHryDFN3+dYyZ6+9uWbErX2kMmjwBwUuwbP8fMegqVPgQsrFbvkw+hN8bboBmFR6earlQLKu7bPB7HdeRfKW6vTbZTks9bar5i07r3dMva5TQfOuD9zUeiMVe7K9Z6awH24fnHO5k/Zfdn+Fbf1WLvPGxVm/zfQ=
  app: sphere-donut
  on:
    repo: commercetools/sphere-donut
